# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #
    # Host
    #
    host_user = ENV['USER'] || ENV['USERNAME']
    host_key_file = "/Users/#{host_user}/.ssh/id_rsa"
    if(File.exist?(host_key_file))
        priv_key = File.read(host_key_file) || nil
        pub_key = File.read("#{host_key_file}.pub") || nil
    end
    #
    # Box
    #
    config.vm.box =  "boxcutter/ubuntu1604"
    config.vm.box_check_update = false

    #
    # Provider
    #
    config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = 4056
       vb.name = Dir.pwd.split('/').last
       vb.linked_clone = true
       vb.customize ["modifyvm", :id, "--vram", "256"]
    end

    #
    # Networking
    #
    config.vm.hostname = Dir.pwd.split('/').last
    config.ssh.forward_x11 = true
    config.ssh.forward_agent = true
    config.ssh.insert_key = false

    config.vm.synced_folder("/", '/Host')

    #
    # Provision
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "chef_solo" do |chef|
        chef.version = '12.10.24'
        chef.channel = 'stable'
        chef.add_recipe 'debian-base-box::init'
        chef.add_recipe 'science::r-base'
        #  passphrase on key stops this from working
        #chef.add_recipe 'debian-base-box::users'
        #chef.add_recipe 'debian-base-box::xorg'
        chef.json = { :users => { :username => host_user, :priv_key => priv_key, :pub_key => pub_key } }
    end

end
