# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #
    # Box
    #
    config.vm.box = "ARTACK/debian-jessie"
    config.vm.box_url = 'https://atlas.hashicorp.com/ARTACK/boxes/debian-jessie'
    config.vm.box_check_update = false


    #
    # Provider
    #
    config.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = 2048
       vb.name = Dir.pwd.split('/').last
       vb.linked_clone = true
     end

    host_user = ENV['USER'] || ENV['USERNAME']
    config.vm.synced_folder("/Users/#{host_user}", '/Host')

    #
    # Networking
    #
    config.vm.hostname = Dir.pwd.split('/').last
    config.ssh.forward_x11 = true
    config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 9042, host: 9042, host_ip: "127.0.0.1"

    #
    # Provision
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "chef_solo" do |chef|
        chef.add_recipe 'debian-dev-box'
        chef.add_recipe 'debian-base-box'
    end

    config.vm.provision "chef_apply" do |chef|
        chef.recipe = '
            remote_file "/home/vagrant/2uda.run" do
                source "http://packages.2ndquadrant.com/2UDA/2UDA-9.5-linux-x64-installer.run"
                mode 0777
                action :create_if_missing
            end

            execute "install-2uda" do
                creates "/opt/2UDA-9.5"
                command "sudo /home/vagrant/2uda.run --mode unattended --pg_password postgres"
            end
            '
    end
end

