source "https://supermarket.chef.io"

#metadata

cookbook 'chocolatey', git: 'https://github.com/chocolatey/chocolatey-cookbook.git'
cookbook 'winbase', path: '../provision/winbase'
cookbook 'debian-dev-box', path: '../provision/debian-dev-box/'
