# -*- mode: ruby -*-
# vi: set ft=ruby :
# vi: set sw=2 :


VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    vm_name = Dir.pwd.split('/').last
    #
    # box
    #
#    config.vm.box_url = "http://aka.ms/vagrant-win81-ie11"
    config.vm.box = "win81"
    config.vm.communicator = "winrm"
    config.winrm.retry_limit = 30
    config.winrm.retry_delay = 10
    config.vm.guest = :windows   # guest detection fails: https://github.com/mitchellh/vagrant/pull/4996
    #
    # provider
    #
    config.vm.provider "virtualbox" do |v|
        v.name = vm_name
        v.gui = true
        v.customize ["modifyvm", :id, "--memory", "2048"]
        v.customize ["modifyvm", :id, "--vram", "256"]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    #
    # network
    #
    config.vm.network "private_network", type: 'dhcp'
    config.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: 5985, host: 5985, id: "winrm", auto_correct: true
    config.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: 3389, host: 3389, id: "rdp", auto_correct: true
    #
    # Provision
    #
    config.vm.provision "chef_solo" do |chef|
        chef.add_recipe 'winbase::init'
        chef.add_recipe 'winbase::git-windows'
        chef.add_recipe 'winbase::python'
        chef.add_recipe 'winbase::rstudio'
        chef.add_recipe 'winbase::qgis'
        chef.add_recipe 'winbase::heidisql'
        chef.json = { :users => { :username => 'vagrant' } }
    end

    host_user = ENV['USER'] || ENV['USERNAME']
    config.vm.synced_folder("/Users/#{host_user}", '/Host')

    config.vm.boot_timeout = 500
end
