source "https://supermarket.chef.io"

#metadata

cookbook 'debian-base-box', path: '../provision/debian-base-box/'
cookbook 'debian-dev-box', path: '../provision/debian-dev-box/'
cookbook 'testing', path: '../provision/testing'
