# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #
    # Host
    #
    host_user = ENV['USER'] || ENV['USERNAME']
    host_key_file = "/Users/#{host_user}/.ssh/id_rsa"
    if(File.exist?(host_key_file))
        priv_key = File.read(host_key_file) || nil
        pub_key  = File.read("#{host_key_file}.pub") || nil
    end
    #
    # Box
    #
    config.vm.box =  "boxcutter/ubuntu1604"
    config.vm.box_check_update = false

    #
    # Provider
    #
    config.vm.provider "virtualbox" do |vb|
       vb.gui          = false
       vb.memory       = 2048
       vb.name         = Dir.pwd.split('/').last
       vb.linked_clone = true
       vb.customize ["modifyvm", :id, "--vram", "256"]
    end

    #
    # Networking
    #
    config.vm.hostname = Dir.pwd.split('/').last
    config.ssh.forward_x11   = true
    config.ssh.forward_agent = true
    config.ssh.insert_key    = false
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", guest_ip: "0.0.0.0", id: 'concourse-atc'
    config.vm.network "forwarded_port", guest: 2222, host: 4444, host_ip: "127.0.0.1", guest_ip: "0.0.0.0", id: 'concourse-tsa'

    config.vm.synced_folder("/Users/#{host_user}", '/Host')

    #
    # Provision
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline     = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "chef_solo" do |chef|
        chef.version = '12.10.24'
        chef.channel = 'stable'
        chef.add_recipe 'debian-base-box::init'
        chef.add_recipe 'testing::concourse'
        chef.json = { :users => { :username => host_user, :priv_key => priv_key, :pub_key => pub_key } }
    end

end
