# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #
    # Host
    #
    host_user = ENV['USER'] || ENV['USERNAME']
    host_key_file = "/Users/#{host_user}/.ssh/id_vagrant"
    if(File.exist?(host_key_file))
        priv_key = File.read(host_key_file) || nil
        pub_key = File.read("#{host_key_file}.pub") || nil
    end
    #
    # Box
    #
    config.vm.box = "ARTACK/debian-jessie"
    config.vm.box_url = 'https://atlas.hashicorp.com/ARTACK/boxes/debian-jessie'
    config.vm.box_check_update = false

    #
    # Provider
    #
    config.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = 2048
       vb.name = Dir.pwd.split('/').last
       vb.linked_clone = true
    end

    #
    # Networking
    #
    config.vm.hostname = Dir.pwd.split('/').last
    config.ssh.forward_x11 = true
    config.ssh.forward_agent = true
    config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", id: 'port8080'
    config.vm.network "forwarded_port", guest: 9042, host: 9042, host_ip: "127.0.0.1", id: 'port9042'

    config.vm.synced_folder("/Users/#{host_user}", '/Host')

    #
    # Provision
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "chef_solo" do |chef|
        chef.add_recipe 'debian-base-box::default'
        chef.add_recipe 'debian-base-box::xorg'
        chef.add_recipe 'debian-base-box::users'
        chef.add_recipe 'debian-dev-box::postgres'
        chef.json = { :users => { :username => host_user, :priv_key => priv_key, :pub_key => pub_key } }
    end

end
