# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

require_relative '../provision/provision-helpers.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.extend(ProvisionHelpers)

    # box

    config.vm.box = "win10"
    config.vm.communicator = "winrm"
    config.vm.guest = :windows   # guest detection fails: https://github.com/mitchellh/vagrant/pull/4996
    config.vm.provider "virtualbox" do |v|
        vm_name = Dir.pwd.split('/').last
        v.name = vm_name
        v.gui = true
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: 5985, host: 55985, id: "winrm", auto_correct: true

    config.vm.provision :shell, path: "../provision/Install-Chocolatey.ps1"

    host_user = ENV['USER'] || ENV['USERNAME']
    config.vm.synced_folder("/Users/#{host_user}", '/Host')
    config.vm.boot_timeout = 800

end
