# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #
    # Box
    #
    config.vm.box = "ARTACK/debian-jessie"
    config.vm.box_url = 'https://atlas.hashicorp.com/ARTACK/boxes/debian-jessie'
    config.vm.box_check_update = false

    #
    # network
    #
    config.ssh.forward_x11 = true
    config.ssh.insert_key = false
    config.vm.hostname = Dir.pwd.split('/').last
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 9042, host: 9042, host_ip: "127.0.0.1"

    #
    # provider
    #
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = 2048
        vb.name = Dir.pwd.split('/').last
        vb.linked_clone = true
    end

    #
    # provision
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    # cassandra
    config.vm.provision(:shell, path: '../provision/oraclejava.sh')
    config.vm.provision(:shell, path: '../provision/cassandra.sh')
    config.vm.network "forwarded_port", guest: 9160, host: 9160, host_ip: "127.0.0.1"

    # cleanup
    config.vm.provision("autoremove", type: :shell, inline: 'apt-get -y autoremove')



end
