# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    #
    # box
    #
    vm_name = Dir.pwd.split('/').last
    config.vm.box       = "jhcook/osx-yosemite-10.10"
    config.vm.box_url   = "jhcook/osx-yosemite-10.10"
    config.ssh.username = 'vagrant'

    #
    # provider
    #
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = vm_name
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    #
    # provision
    #
    config.vm.provision(:shell, path: '../provision/xcode-cli-tools.sh')
    host_conf_dir = File.expand_path("~/Config")
    if(Dir.exists?(host_conf_dir))
        config.vm.synced_folder host_conf_dir, "/Users/vagrant/Config", id: "host-config", type: "rsync"
    else
        config.vm.provision(:shell, privileged: false, inline: "cd /Users/vagrant/ && git clone 'https://github.com/byrney/Config.git'")
    end
    config.vm.provision(:shell, privileged: false, inline: 'cd /Users/vagrant/Config && bash install.sh rob.cfg')
    config.vm.provision(:shell, privileged: false, inline: 'cd /Users/vagrant/Config/Setup && bash mbpsetup.sh kat.bash')
    config.vm.provision(:shell, privileged: false, inline: 'curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh')
end
