# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    #
    # Host
    #
    host_conf_dir = File.expand_path("~/Config")
    host_setup_dir = File.expand_path("~/Setup")

    #
    # Box
    #
    vm_name = Dir.pwd.split('/').last
    config.vm.box       = "monsenso/macos-10.13"
    config.vm.box_url   = "monsenso/macos-10.13"

    #
    # Provider
    #
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = vm_name
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    #
    # Network
    #
    config.ssh.forward_agent = true
    config.ssh.forward_env = ["LANG", "LC_KBD_LAYOUT"]
    config.ssh.username = 'vagrant'

    #
    # Provision
    #
    config.vm.synced_folder ".", "/vagrant", disabled: true
    if(Dir.exists?(host_conf_dir))
        config.vm.synced_folder host_conf_dir, "/Users/vagrant/Config", id: "host-config", type: "rsync", rsync__chown: false
    end
    if(Dir.exists?(host_setup_dir))
        config.vm.synced_folder host_setup_dir, "/Users/vagrant/Setup", id: "host-setup", type: "rsync", rsync__chown: false
    else
        config.vm.provision(:shell, privileged: false, inline: "cd /Users/vagrant/ && git clone 'https://github.com/byrney/OsxSetup.git' Setup")
    end
    config.vm.provision "hostname", type: "shell" do |s|
        s.inline = "
            scutil --set ComputerName '#{vm_name}'
            scutil --set HostName '#{vm_name}'
            scutil --set LocalHostName '#{vm_name}'
            defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string '#{vm_name}'
        "
    end
    # xcode headless install moved to Setup
#    config.vm.provision(:shell, path: '../provision/xcode-cli-tools.sh')
    config.vm.provision(:shell, privileged: false, inline: 'cd /Users/vagrant/Setup && bash mbpsetup.sh dev.bash')
    config.vm.provision(:shell, privileged: false, inline: 'cd /Users/vagrant/Config && bash install.sh rob.cfg')
    #config.vm.provision(:shell, privileged: false, inline: 'curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh')
end
