# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #
    # Host
    #
    host_user = ENV['USER'] || ENV['USERNAME']
    host_key_file = "/Users/#{host_user}/.ssh/id_vagrant"
    if(File.exist?(host_key_file))
        priv_key = File.read(host_key_file) || nil
        pub_key = File.read("#{host_key_file}.pub") || nil
    end
    #
    # Box
    #
    config.vm.box = "ARTACK/debian-jessie"
    config.vm.box_url = 'https://atlas.hashicorp.com/ARTACK/boxes/debian-jessie'
    config.vm.box_check_update = false

    #
    # Provider
    #
    config.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = 2048
       vb.name = Dir.pwd.split('/').last
       vb.linked_clone = true
       vb.customize ["modifyvm", :id, "--vram", "256"]
    end

    #
    # Networking
    #
    config.vm.hostname = Dir.pwd.split('/').last
    config.ssh.forward_x11 = true
    config.ssh.forward_agent = true
    config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", id: 'omnihttp'
    config.vm.network "forwarded_port", guest: 2000, host: 2000, host_ip: "127.0.0.1", id: 'omniws'

    config.vm.synced_folder("/Users/#{host_user}", '/Host')

    #
    # Provision
    #
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "chef_solo" do |chef|
        chef.add_recipe 'debian-base-box::default'
        chef.add_recipe 'debian-base-box::xorg'
        chef.add_recipe 'debian-base-box::users'
        chef.add_recipe 'debian-dev-box::postgres'
        chef.add_recipe 'debian-dev-box::omnidb'
        chef.json = { :users => { :username => host_user, :priv_key => priv_key, :pub_key => pub_key } }
    end
    #
    # add omnidb user
    #
    config.vm.provision "user-omnidb", type: "shell" do |s|
        s.inline = "sudo omnidb-config-server -c vagrant vagrant"
    end
    #
    # STart server
    #
    config.vm.provision "start-omnidb", type: "shell", run: 'always' do |s|
        s.inline = "sudo omnidb-server -p 8080 -w 2000 &"
    end
end
